### PR TITLE
add a GetWithTTL method in the cache

### LINKED ISSUE #49: Add a GetWithTTL method
Since we have a SetWithTTL it would be nice to know how much remain time an item has for expired when we recover it from the cache. 
`func GetWithTTL(key) (data, ttl, err)`

### PR DESCRIPTION
**Pull request by asgarciap**
Fixes #49

### CODE REVIEW

**Comment by asgarciap** [comment]
**Tests Results:**
```bash
go test -cover -race -count=1 -timeout=30s -run .
PASS
coverage: 96.1% of statements
ok      github.com/ReneKroon/ttlcache/v2        13.165s

go test -covermode=count -coverprofile=coverage.out -timeout=90s -run .
PASS
coverage: 96.1% of statements
ok      github.com/ReneKroon/ttlcache/v2        12.482s

go test -bench=. -benchmem
goos: linux
goarch: amd64
pkg: github.com/ReneKroon/ttlcache/v2/bench
cpu: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
BenchmarkCacheSetWithoutTTL-8            1000000              1627 ns/op             265 B/op          3 allocs/op
BenchmarkCacheSetWithGlobalTTL-8          747896              2054 ns/op             104 B/op          3 allocs/op
BenchmarkCacheSetWithTTL-8                748890              2173 ns/op             103 B/op          3 allocs/op
PASS
ok      github.com/ReneKroon/ttlcache/v2/bench  4.856s
```

**Comment by ReneKroon** [comment]
Hello, 

sorry for the late reply, it's a bit busy over here. I do plan to add the functionality however i see that your change breaks compatibility by changing a public method. I will need to invest some proper time to see if we can work around this, or that indeed this should trigger version 3.

Greetings,

Rene

**Comment by asgarciap** [comment]
> Hello,
> 
> sorry for the late reply, it's a bit busy over here. I do plan to add the functionality however i see that your change breaks compatibility by changing a public method. I will need to invest some proper time to see if we can work around this, or that indeed this should trigger version 3.
> 
> Greetings,
> 
> Rene

Ahhh you are right, the GetByLoader method is public :D ... I can also add a new public method named GetByLoaderWithTTL to avoid breaking the API.

Would that be ok?

**Comment by ReneKroon** [comment]
That would be good. Any cleanup and reconciliation of those would be part of a v3 release, so for now let's add the extra method

**Comment by asgarciap** [comment]
```
go test -cover -race -count=1 -timeout=30s -run .

PASS
coverage: 96.5% of statements
ok      github.com/ReneKroon/ttlcache/v2        12.844s

go test -covermode=count -coverprofile=coverage.out -timeout=90s -run .

PASS
coverage: 96.5% of statements
ok      github.com/ReneKroon/ttlcache/v2        12.447s

go test -bench=. -benchmem

goos: linux
goarch: amd64
pkg: github.com/ReneKroon/ttlcache/v2/bench
cpu: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
BenchmarkCacheSetWithoutTTL-8             964172              1586 ns/op             271 B/op          3 allocs/op
BenchmarkCacheSetWithGlobalTTL-8          778461              2054 ns/op             104 B/op          3 allocs/op
BenchmarkCacheSetWithTTL-8                746583              2059 ns/op             104 B/op          3 allocs/op
PASS
ok      github.com/ReneKroon/ttlcache/v2/bench  4.730s

```

**Comment by ReneKroon** [comment]
Looks good, merging from hammock so version's release will follow this week

**Comment by ReneKroon** [comment]
It's now officially released in v2.8.0

**Pull request merged**
