### PR TITLE
Added cache limit

### PR DESCRIPTION
**Pull request by TwoAbove**
This PR adds a cache limiter.

This is something that we need to keep the cache from growing too large if we have a spike in caching.

### CODE REVIEW

**Comment by TwoAbove** [comment]
I'm not sure what's wrong with the CI, though. It seems that It's passing and then returning 1?

**Comment by TwoAbove** [comment]
Thanks @ReneKroon !

**Comment by ReneKroon** [comment]
One note, the test does'nt check that indeed the last added items are in the cache. Can you fix that? I have no other comments and will merge after checking the build status manually (i'll accept that Travis cannot work with remote MR's at this time and fix that later)

**Comment by TwoAbove** [comment]
@ReneKroon Updated the test to assert that only the last 10 are present

**Comment by TwoAbove** [comment]
@ReneKroon Thank you!

**Comment by ReneKroon** [comment]
released as v2.1.0

**Pull request merged**
