### PR TITLE
add customer loader function for each Get()

### PR DESCRIPTION
**Pull request by witchu**
Use case: Web Server cache middleware.

The middleware can hook the requests and cache the responses.

Example:
```
func NewPathQueryCache(cache *ttlcache.Cache) fiber.Handler {
	return func(c *fiber.Ctx) error {
		path := c.Path()
		query := c.Request().URI().QueryString()

		key := path + "|" + string(query)

		r, err := cache.Get(key, func(string) (data interface{}, ttl time.Duration, err error) {
			begin := time.Now()
			err = c.Next()
			if err != nil {
				return
			}
			ttl = time.Since(begin) * 120
			resp := c.Response()
			data = &cacheEntry{
				code: resp.StatusCode(),
				body: resp.Body(),
			}
			return
		})
		if err != nil {
			return errors.Wrap(err, "cache get failed")
		}

		result, ok := r.(*cacheEntry)
		if !ok {
			return errors.Wrap(err, "cache cast failed")
		}

		return c.Status(result.code).Send(result.body)
	}
}
```

Thank you for a good library.

### CODE REVIEW

**Comment by ReneKroon** [comment]
Hi, I'm thinking about the long term way to integrate. I understand your case, where you essentially have a compound key. Another option that I like slightly less is to make the key an interface {} as well.

**Comment by ReneKroon** [comment]
Unfortunately i can't really make up my mind whether this is a good long term change. I think i need provide a few interfaces to distinguish between a simple and advanced cache. 

I don't have a timeline for you but i will put this in an 'advanced' interface when i create them.

**Comment by jspri** [comment]
I have a similar use case to the OP - I have compound keys and I also want to be able to pass the context from the current request through to the getter. I also have a hunch the code might write more naturally if you define the getter at the same time as the get being called.

Otherwise love the library - best cache I found for my use case after looking through a fair few.

**Comment by ReneKroon** [comment]
ok, i will merge this. Full version release will come when i have added some tests and add a simple interface for basic usage.

**Comment by ReneKroon** [comment]
The function will be *GetByLoader* in the release. Else it's impossible to split off a 'regular' *Get* function for the SimpleCache interface due to overloading which is not allowed in Go.

**Pull request merged**
