### PR TITLE
Loaderfunction key not found

### LINKED ISSUE #44: Low timeout loader function race
After running this for a while I noticed it's possible to get a key not found error (`ErrNotFound`), even when using a loader function. Repro below.

```go
// Cache sometimes returns key not found under parallel access with a loader function
func TestCache_TestLoaderFunctionParallelKeyAccess(t *testing.T) {
	t.Parallel()
	cache := NewCache()

	cache.SetLoaderFunction(func(key string) (data interface{}, ttl time.Duration, err error) {
		time.Sleep(time.Millisecond*300)
		return "1", 1*time.Nanosecond, nil
	})


	wg := sync.WaitGroup{}
	errCount := uint64(0)
	for i:=0; i<200; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			value, found := cache.Get("foo")
			if value != "1" || found != nil { // Use an atomic to avoid spamming logs
				atomic.AddUint64(&errCount, 1)
			}
		}()

	}

	wg.Wait()

	assert.Equalf(t, uint64(0), errCount, "expected 0 errs, got %d", errCount)

	cache.Close()
}
```

I spent a while trying to distill this down further, and I _think_ it occurs when:
- The TTL is low (10ms when I first noticed the bug - probably low enough that it could be triggered by a GC cycle)
- Multiple goroutines try to access the same key at the same time
- Some goroutines block while waiting for the loaderFunction
- By the time they unblock the freshly set key has already expired!

I think it would be more consistent if the blocked goroutines **always** got the output of the loaderfunction that they were blocked by. I would probably use [singleflight](https://pkg.go.dev/golang.org/x/sync/singleflight), but there might be a cleaner way to do it.

If you think it's a good idea then I'm happy to put together a PR.

### PR DESCRIPTION
**Pull request by jspri**
Fixes #44

I ran into some trouble where `TestCache_Limit` didn't work for me locally but that was the same before and after the change (length was 10 but keys were incorrect - this might be due to shitty windows timers).

Let me know any thoughts.

### CODE REVIEW

**Review by ReneKroon — APPROVED** [review]
checked the test case on previous branch, indeed this looks good.
also checked for proper locking, but since the setting the value is done in the end with 'SetTTL', the locking is ok.

**Comment by jspri** [comment]
Thinking about this some more I think I've introduced a potential race where the loader function can get called again immediately after it returns if the locking happens in a certain order... It's probably easiest to explain with what I think the fix is...

```go
if loaderFunction != nil && !exists {
	ch := cache.loaderLock.DoChan(key, func() (interface{}, error) {
		// cache is not blocked during io
		invokeData, err := cache.invokeLoader(key, loaderFunction)
		return invokeData, err
	})
	// Unlock occurs after DoChan to prevent race where the loader function could be called twice
	// This relies on the loader not being able to return until the cache mutex is released
	cache.mutex.Unlock()
	res := <-ch
	dataToReturn = res.Val
	err = res.Err
}
```
 I couldn't reproduce it with a test though and I'm not super experienced with multithreaded stuff so not sure where to go next 😆

**Comment by ReneKroon** [comment]
i do agree that there's a window where a second request can be made. However i see this as a worst-case behaviour: 2 requests might be made for any key that is still to be loaded. I think that's better than locking the *whole* cache for the duration of the external call.

**Comment by jspri** [comment]
I agree waiting for the whole duration of the external call would be pretty bad.

I _think_ we get around that here by using the channel though (`DoChan` instead of `Do`)

**Comment by ReneKroon** [comment]
```go
func TestCache_GetByLoaderRace(t *testing.T) {
	t.Parallel()
	cache := NewCache()
	cache.SetTTL(time.Microsecond)
	defer cache.Close()

	loaderInvocations := uint64(0)
	inFlight := uint64(0)

	globalLoader := func(key string) (data interface{}, ttl time.Duration, err error) {
		atomic.AddUint64(&inFlight, 1)
		atomic.AddUint64(&loaderInvocations, 1)
		time.Sleep(time.Microsecond)
		assert.Equal(t, uint64(1), inFlight)
		defer atomic.AddUint64(&inFlight, ^uint64(0))
		return "global", 0, nil

	}
	cache.SetLoaderFunction(globalLoader)

	wg := sync.WaitGroup{}
	for i := 0; i < 1000; i++ {
		wg.Add(1)
		go func() {
			key, _ := cache.Get("test")
			assert.Equal(t, "global", key)
			wg.Done()

		}()
	}
	wg.Wait()

	assert.Equal(t, uint64(1), loaderInvocations)
}
```

This type of test shows me more than one loaderInvocations but i never detect 2 in flight. I still think your argument has merit, but i'd like to better understand the cases where this happens.

**Comment by ReneKroon** [comment]
[Issue45_bench.csv](https://github.com/ReneKroon/ttlcache/files/6607350/Issue45_bench.csv)

Indeed the snippet you posted is better: It reduces amount of fetches by ~50% with the median moving from 5 fetches per 1000 requests to 2 fetches per 1000 requests as seen in the above benchmark

**Comment by ReneKroon** [comment]
In fact the method of using specific channels to sync parts that contain multiple mutex lock/unlock operations could be the paradigm to do something in ttlcache V3 that is not possible in V2 ! My mind is blown for now and i hope you can understand that i needed to have some proof to make this change. It's my way of guaranteeing quality in this library: if something is better then we can do it for sure, if unsure then better find out how and why before doing random stuff.

**Comment by jspri** [comment]
Nice benchmark! All good with the delay, I was a bit too hasty with the original PR. Thanks again for the great lib.

**Pull request merged**
