### PR TITLE
Use type parameters

### PR DESCRIPTION
**Pull request by swithek**
This PR adds type parameters to all the relevant types and functions. The logic of the functions and their tests has not been changed.

Other changes worth mentioning:
- The top-level documentation comments have been reformatted (mainly missing periods have been added). The content of those comments has not been changed.
- For the sake of consistency, some fields/variables have been renamed from 'data' to 'value'.
- The go version specified in go.mod has been changed to 1.18.
- Readme.md has been renamed to README.md.

Closes: #63

### CODE REVIEW

**Comment by swithek** [comment]
@ReneKroon do you have any other changes planned for the next major version? If the changes here are acceptable, I think this PR can be merged into a v3-dev branch and released after the release of go1.18.

**Comment by ReneKroon** [comment]
do you want to use this in a preliminary release (ie. 3.0.0-beta ) already? I'll let this become the main version as soon as go 1.18 is released.

**Comment by ReneKroon** [comment]
Beta release created: v3.0.0-beta

**Comment by dolmen** [comment]
Go 1.18 has been released.

**Comment by ReneKroon** [comment]
I will handover the project on Wednesday. Expect changes soon after that

**Pull request merged**
